### ISSUE TITLE
returned non-zero exit status 4294967294.

### ISSUE THREAD

**Issue by S0LTIS** [sh570655308/ComfyUI-GigapixelAI#12]
# ComfyUI Error Report
## Error Details
- **Node ID:** 155
- **Node Type:** GigapixelAI
- **Exception Type:** subprocess.CalledProcessError
- **Exception Message:** Command '['C:\\Program Files\\Topaz Labs LLC\\Topaz Gigapixel AI\\gigapixel.exe', '--scale', '2.0', '-i', 'C:\\COMFYUI\\COMFYU2\\CFUI2\\ComfyUI\\temp\\gigapixel_output\\batch_1743816061147\\input_1.png', '-o', 'C:\\COMFYUI\\COMFYU2\\CFUI2\\ComfyUI\\temp\\gigapixel_output\\batch_1743816061147\\output_1', '--dn', '1.0', '--sh', '1.0', '--cm', '67.0', '--fr', '50.0', '--model', 'fidelity', '--mv', '2']' returned non-zero exit status 4294967294.
## Stack Trace
```
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\ComfyUI-GigapixelAI\gigapixel.py", line 146, in upscale_image
    (settings, output_image_paths) = self.gigapixel_upscale(img_file, gigapixel_exe, scale, upscale, model, output_dir)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\ComfyUI-GigapixelAI\gigapixel.py", line 210, in gigapixel_upscale
    result = subprocess.run(
             ^^^^^^^^^^^^^^^

  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,

```
## System Information
- **ComfyUI Version:** 0.3.27
- **Arguments:** main.py --lowvram --preview-method auto --auto-launch
- **OS:** nt
- **Python Version:** 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.6.0+cu126
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3050 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 6441795584
  - **VRAM Free:** 4672424076
  - **Torch VRAM Total:** 771751936
  - **Torch VRAM Free:** 113215628

## Logs
```
2025-04-04T16:57:52.031040 - 
[Tiled VAE]: Executing Decoder Task Queue:  98%|██████████████████████████████████▎| 723/738 [00:02<00:00, 278.31it/s]2025-04-04T16:57:52.101571 - 
[Tiled VAE]: Executing Decoder Task Queue: 100%|███████████████████████████████████| 738/738 [00:02<00:00, 254.81it/s]2025-04-04T16:57:52.101571 - 
2025-04-04T16:57:52.740896 - [Tiled VAE]: Done in 4.277s, max VRAM alloc 1580.750 MB2025-04-04T16:57:52.740896 - 
2025-04-04T16:57:53.075576 - 0 models unloaded.
2025-04-04T16:57:53.081670 - loaded partially 128.0 127.99993133544922 0
2025-04-04T16:58:27.888852 - 0 models unloaded.
2025-04-04T16:58:27.920119 - loaded partially 128.0 127.99993133544922 0
2025-04-04T16:58:32.204776 - Requested to load SDXL
2025-04-04T16:58:34.032361 - loaded partially 3091.685210296631 3091.6845779418945 0
2025-04-04T17:01:49.390832 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [03:15<00:00,  9.72s/it]2025-04-04T17:01:49.391904 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [03:15<00:00,  9.77s/it]2025-04-04T17:01:49.391904 - 
2025-04-04T17:01:49.398453 - Requested to load AutoencoderKL
2025-04-04T17:01:54.297062 - 0 models unloaded.
2025-04-04T17:01:54.370728 - loaded partially 128.0 127.99993133544922 0
2025-04-04T17:02:13.718608 - 
2025-04-04T17:02:14.801996 - 0: 640x480 1 face, 106.1ms
2025-04-04T17:02:14.801996 - Speed: 31.3ms preprocess, 106.1ms inference, 154.0ms postprocess per image at shape (1, 3, 640, 480)
2025-04-04T17:02:16.999880 - CLIP: [Awe, Tongue]2025-04-04T17:02:16.999880 - 
2025-04-04T17:02:30.228106 - Detailer: force inpaint2025-04-04T17:02:30.228106 - 
2025-04-04T17:02:30.231631 - Detailer: segment upscale for ((422.40912, 466.5565)) | crop region (1267, 1399) x 1.0 -> (1267, 1399)2025-04-04T17:02:30.231631 - 
2025-04-04T17:02:30.653872 - 0 models unloaded.
2025-04-04T17:02:30.662452 - loaded partially 128.0 127.99993133544922 0
2025-04-04T17:02:32.469664 - 0 models unloaded.
2025-04-04T17:02:32.474674 - loaded partially 128.0 127.99993133544922 0
2025-04-04T17:02:33.995214 - Requested to load SDXL
2025-04-04T17:02:37.399748 - loaded partially 3159.5156791687014 3159.515380859375 544
2025-04-04T17:05:40.709828 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [03:03<00:00,  4.39s/it]2025-04-04T17:05:40.710835 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [03:03<00:00,  4.07s/it]2025-04-04T17:05:40.711230 - 
2025-04-04T17:05:40.805019 - 0 models unloaded.
2025-04-04T17:05:40.837211 - loaded partially 3159.5153809547423 3159.515380859375 0
2025-04-04T17:08:44.860325 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [03:04<00:00,  4.04s/it]2025-04-04T17:08:44.860325 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [03:04<00:00,  4.09s/it]2025-04-04T17:08:44.860325 - 
2025-04-04T17:08:44.862333 - Requested to load AutoencoderKL
2025-04-04T17:08:46.359386 - 0 models unloaded.
2025-04-04T17:08:46.409786 - loaded partially 128.0 127.99993133544922 0
2025-04-04T17:08:48.653061 - [Impact Pack] vae decoded in 3.8s2025-04-04T17:08:48.653061 - 
2025-04-04T17:08:49.374175 - 
2025-04-04T17:08:49.686950 - 0: 640x480 1 hand, 75.6ms
2025-04-04T17:08:49.686950 - Speed: 3.5ms preprocess, 75.6ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 480)
2025-04-04T17:08:50.766596 - CLIP: [Puzzlement, Dimples]2025-04-04T17:08:50.766596 - 
2025-04-04T17:08:54.421872 - Detailer: force inpaint2025-04-04T17:08:54.421872 - 
2025-04-04T17:08:54.421872 - Detailer: segment upscale for ((298.24228, 257.65662)) | crop region (894, 773) x 1.0 -> (894, 773)2025-04-04T17:08:54.421872 - 
2025-04-04T17:08:54.599831 - loaded completely 1665.6264457702637 159.55708122253418 True
2025-04-04T17:08:55.794940 - Requested to load SDXL
2025-04-04T17:08:57.356902 - loaded partially 3132.6529739379885 3132.652587890625 550
2025-04-04T17:10:21.140083 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:23<00:00,  1.87s/it]2025-04-04T17:10:21.140083 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:23<00:00,  1.86s/it]2025-04-04T17:10:21.140083 - 
2025-04-04T17:10:21.239201 - 0 models unloaded.
2025-04-04T17:10:21.272679 - loaded partially 3132.6525879859923 3132.652587890625 0
2025-04-04T17:11:45.091002 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:23<00:00,  1.83s/it]2025-04-04T17:11:45.092001 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:23<00:00,  1.86s/it]2025-04-04T17:11:45.092001 - 
2025-04-04T17:11:45.094002 - Requested to load AutoencoderKL
2025-04-04T17:11:45.395171 - loaded completely 251.56888961791992 159.55708122253418 True
2025-04-04T17:11:46.142008 - [Impact Pack] vae decoded in 1.0s2025-04-04T17:11:46.142008 - 
2025-04-04T17:11:47.289012 - !!! Exception during processing !!! Gigapixel AI not found: 
2025-04-04T17:11:47.292551 - Traceback (most recent call last):
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\ComfyUI-GigapixelAI\gigapixel.py", line 146, in upscale_image
    (settings, output_image_paths) = self.gigapixel_upscale(img_file, gigapixel_exe, scale, upscale, model, output_dir)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\ComfyUI-GigapixelAI\gigapixel.py", line 165, in gigapixel_upscale
    raise ValueError(f'Gigapixel AI not found: {gigapixel_exe}')
ValueError: Gigapixel AI not found: 

2025-04-04T17:11:47.295551 - Prompt executed in 983.15 seconds
2025-04-04T21:05:27.561399 - got prompt
2025-04-04T21:05:27.597760 - Failed to validate prompt for output 94:
2025-04-04T21:05:27.597760 - * VRAMCleanup 85:
2025-04-04T21:05:27.597760 -   - Required input is missing: anything
2025-04-04T21:05:27.597760 - Output will be ignored
2025-04-04T21:05:27.598767 - Failed to validate prompt for output 149:
2025-04-04T21:05:27.598767 - * (prompt):
2025-04-04T21:05:27.598767 -   - Required input is missing: images
2025-04-04T21:05:27.599769 - * SaveImagePlus 149:
2025-04-04T21:05:27.599769 -   - Required input is missing: images
2025-04-04T21:05:27.599769 - Output will be ignored
2025-04-04T21:05:27.617046 - Failed to validate prompt for output 9:
2025-04-04T21:05:27.618048 - * polymath_settings 31:
2025-04-04T21:05:27.618048 -   - Value 0 smaller than min of 1: ollama_keep_alive
2025-04-04T21:05:27.618561 - Output will be ignored
2025-04-04T21:05:27.618561 - Failed to validate prompt for output 30:
2025-04-04T21:05:27.618561 - Output will be ignored
2025-04-04T21:05:27.619573 - Failed to validate prompt for output 85:
2025-04-04T21:05:27.619573 - * (prompt):
2025-04-04T21:05:27.619573 -   - Required input is missing: anything
2025-04-04T21:05:27.619573 - Output will be ignored
2025-04-04T21:05:27.621573 - Failed to validate prompt for output 64:
2025-04-04T21:05:27.621573 - Output will be ignored
2025-04-04T21:05:27.621573 - Failed to validate prompt for output 82:
2025-04-04T21:05:27.621573 - Output will be ignored
2025-04-04T21:05:27.621573 - Failed to validate prompt for output 63:
2025-04-04T21:05:27.622570 - Output will be ignored
2025-04-04T21:05:27.747587 - [92mPolymath Chat Request: [0mModel='Ollama: trollek/qwen2-diffusion-prompter latest', Prompt='Please provide only the SDXL prompt, nothing extra.

Please describe an emotive sequence stunning solo adult female portrait. Any dramatic setting. in a random pose.

Please only give me the prompt.

Please expand this prompt with a lot more fictional detail, no adult theme
', Additional Text=''2025-04-04T21:05:27.747587 -  2025-04-04T21:05:27.748590 - Seed='13341287', Web Search Enabled=False, Keep Context=False,Ollama Chat Mode=False, Custom Instruction='expert prompter'2025-04-04T21:05:27.748590 - 
2025-04-04T21:05:34.580242 - Ollama API Response:2025-04-04T21:05:34.580242 -  2025-04-04T21:05:34.580242 - A detailed and imaginative digital illustration of a woman's face, dressed in bold colors, posing as an erotic scene on a beach, surrounded by palm trees and colorful coral. The sun is setting, casting long shadows across the water.2025-04-04T21:05:34.580242 - 
2025-04-04T21:05:40.141158 - loaded partially 3155.5527008056642 3155.552375793457 0
2025-04-04T21:07:07.783427 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:27<00:00,  1.75s/it]2025-04-04T21:07:07.783427 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:27<00:00,  1.95s/it]2025-04-04T21:07:07.783427 - 
2025-04-04T21:07:07.794463 - Requested to load AutoencoderKL
2025-04-04T21:07:08.104459 - loaded completely 219.12644577026367 159.55708122253418 True
2025-04-04T21:07:08.622802 - [Tiled VAE]: input_size: torch.Size([1, 4, 128, 96]), tile_size: 64, padding: 112025-04-04T21:07:08.622802 - 
2025-04-04T21:07:08.622802 - [Tiled VAE]: split to 2x2 = 4 tiles. Optimal tile size 64x64, original tile size 64x642025-04-04T21:07:08.622802 - 
2025-04-04T21:07:08.636356 - [Tiled VAE]: Fast mode enabled, estimating group norm parameters on 48 x 64 image2025-04-04T21:07:08.636356 - 
2025-04-04T21:07:09.934897 - 
[Tiled VAE]: Executing Decoder Task Queue:  75%|██████████████████████████▎        | 370/492 [00:01<00:00, 357.75it/s]2025-04-04T21:07:09.975372 - 
[Tiled VAE]: Executing Decoder Task Queue: 100%|███████████████████████████████████| 492/492 [00:01<00:00, 444.08it/s]2025-04-04T21:07:09.975372 - 
2025-04-04T21:07:10.569193 - [Tiled VAE]: Done in 2.461s, max VRAM alloc 2189.997 MB2025-04-04T21:07:10.570702 - 
2025-04-04T21:07:12.267063 - loaded partially 3155.5277565002443 3155.526741027832 0
2025-04-04T21:07:48.143870 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:35<00:00,  1.76s/it]2025-04-04T21:07:48.144874 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:35<00:00,  1.79s/it]2025-04-04T21:07:48.144874 - 
2025-04-04T21:07:48.418142 - Requested to load AutoencoderKL
2025-04-04T21:07:49.376843 - 0 models unloaded.
2025-04-04T21:07:49.412501 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:07:49.885767 - [Tiled VAE]: input_size: torch.Size([1, 4, 192, 144]), tile_size: 64, padding: 112025-04-04T21:07:49.885767 - 
2025-04-04T21:07:49.885767 - [Tiled VAE]: split to 3x2 = 6 tiles. Optimal tile size 64x64, original tile size 64x642025-04-04T21:07:49.885767 - 
2025-04-04T21:07:49.887771 - [Tiled VAE]: Fast mode enabled, estimating group norm parameters on 48 x 64 image2025-04-04T21:07:49.887771 - 
2025-04-04T21:07:52.952998 - 
[Tiled VAE]: Executing Decoder Task Queue:  98%|██████████████████████████████████▏| 722/738 [00:02<00:00, 279.14it/s]2025-04-04T21:07:53.021810 - 
[Tiled VAE]: Executing Decoder Task Queue: 100%|███████████████████████████████████| 738/738 [00:02<00:00, 253.48it/s]2025-04-04T21:07:53.021810 - 
2025-04-04T21:07:53.538047 - [Tiled VAE]: Done in 4.124s, max VRAM alloc 1690.933 MB2025-04-04T21:07:53.538047 - 
2025-04-04T21:07:53.761583 - 0 models unloaded.
2025-04-04T21:07:53.766660 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:08:26.514520 - Requested to load AutoencoderKL
2025-04-04T21:08:26.569412 - 0 models unloaded.
2025-04-04T21:08:26.670831 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:08:31.573611 - Requested to load SDXL
2025-04-04T21:08:32.621026 - loaded partially 2977.5014944763184 2977.5012283325195 0
2025-04-04T21:12:04.889460 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [03:32<00:00, 10.67s/it]2025-04-04T21:12:04.890459 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [03:32<00:00, 10.61s/it]2025-04-04T21:12:04.890459 - 
2025-04-04T21:12:04.896503 - Requested to load AutoencoderKL
2025-04-04T21:12:10.835791 - 0 models unloaded.
2025-04-04T21:12:11.002680 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:12:28.870971 - 
2025-04-04T21:12:29.512324 - 0: 640x480 1 face, 100.8ms
2025-04-04T21:12:29.512324 - Speed: 22.2ms preprocess, 100.8ms inference, 45.5ms postprocess per image at shape (1, 3, 640, 480)
2025-04-04T21:12:31.925009 - CLIP: [Pride, Tear ducts]2025-04-04T21:12:31.925009 - 
2025-04-04T21:12:47.505987 - Detailer: force inpaint2025-04-04T21:12:47.505987 - 
2025-04-04T21:12:47.506996 - Detailer: segment upscale for ((554.12775, 556.699)) | crop region (1662, 1670) x 1.0 -> (1662, 1670)2025-04-04T21:12:47.506996 - 
2025-04-04T21:12:48.142301 - 0 models unloaded.
2025-04-04T21:12:48.152447 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:12:50.980206 - 0 models unloaded.
2025-04-04T21:12:50.990234 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:12:53.431211 - Requested to load SDXL
2025-04-04T21:12:55.772498 - loaded partially 3143.70238571167 3143.7017822265625 547
2025-04-04T21:12:55.779656 - 
  0%|                                                                                          | 0/45 [00:00<?, ?it/s]2025-04-04T21:13:01.814819 - 
  0%|                                                                                          | 0/45 [00:06<?, ?it/s]2025-04-04T21:13:01.814819 - 
2025-04-04T21:13:01.840245 - !!! Exception during processing !!! Allocation on device 
2025-04-04T21:13:02.270249 - Traceback (most recent call last):
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 626, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 580, in enhance_face
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 340, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\core.py", line 365, in enhance_detail
    refined_latent = impact_sampling.ksampler_wrapper(model2, seed2, steps2, cfg2, sampler_name2, scheduler2, positive2, negative2,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 205, in ksampler_wrapper
    refined_latent = separated_sample(model, True, seed, advanced_steps, cfg, sampler_name, scheduler,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 178, in separated_sample
    res = sample_with_custom_noise(model, add_noise, seed, cfg, positive, negative, impact_sampler, sigmas, latent_image, noise=noise, callback=callback)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 122, in sample_with_custom_noise
    samples = comfy.sample.sample_custom(model, noise, cfg, sampler, sigmas, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\sample.py", line 50, in sample_custom
    samples = comfy.samplers.sample(model, noise, positive, negative, cfg, model.load_device, sampler, sigmas, model_options=model.model_options, latent_image=latent_image, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\samplers.py", line 1023, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\samplers.py", line 1008, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\samplers.py", line 976, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\samplers.py", line 959, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\samplers.py", line 738, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 67, in sampler_function_wrapper
    return orig_sampler_function(model, x, sigmas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\k_diffusion\sampling.py", line 873, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\k_diffusion\sampling.py", line 778, in sample_dpmpp_2m_sde
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\samplers.py", line 736, in <lambda>
    k_callback = lambda x: callback(x["i"], x["denoised"], x["x"], total_steps)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\latent_preview.py", line 105, in callback
    preview_bytes = previewer.decode_latent_to_preview_image(preview_format, x0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\latent_preview.py", line 27, in decode_latent_to_preview_image
    preview_image = self.decode_latent_to_preview(x0)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\latent_preview.py", line 35, in decode_latent_to_preview
    x_sample = self.taesd.decode(x0[:1])[0].movedim(0, 2)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\taesd\taesd.py", line 74, in decode
    x_sample = self.taesd_decoder((x - self.vae_shift) * self.vae_scale)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\comfy\ops.py", line 101, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
torch.OutOfMemoryError: Allocation on device 

2025-04-04T21:13:02.276287 - Got an OOM, unloading all loaded models.
2025-04-04T21:13:04.187323 - Prompt executed in 456.56 seconds
2025-04-04T21:13:34.751593 - got prompt
2025-04-04T21:13:34.782743 - Failed to validate prompt for output 94:
2025-04-04T21:13:34.782743 - * VRAMCleanup 85:
2025-04-04T21:13:34.782743 -   - Required input is missing: anything
2025-04-04T21:13:34.782743 - Output will be ignored
2025-04-04T21:13:34.783746 - Failed to validate prompt for output 149:
2025-04-04T21:13:34.783746 - * (prompt):
2025-04-04T21:13:34.783746 -   - Required input is missing: images
2025-04-04T21:13:34.784260 - * SaveImagePlus 149:
2025-04-04T21:13:34.784260 -   - Required input is missing: images
2025-04-04T21:13:34.784260 - Output will be ignored
2025-04-04T21:13:34.801822 - Failed to validate prompt for output 9:
2025-04-04T21:13:34.802332 - * polymath_settings 31:
2025-04-04T21:13:34.802332 -   - Value 0 smaller than min of 1: ollama_keep_alive
2025-04-04T21:13:34.802332 - Output will be ignored
2025-04-04T21:13:34.802332 - Failed to validate prompt for output 30:
2025-04-04T21:13:34.802332 - Output will be ignored
2025-04-04T21:13:34.802332 - Failed to validate prompt for output 85:
2025-04-04T21:13:34.802332 - * (prompt):
2025-04-04T21:13:34.802332 -   - Required input is missing: anything
2025-04-04T21:13:34.802332 - Output will be ignored
2025-04-04T21:13:34.803841 - Failed to validate prompt for output 64:
2025-04-04T21:13:34.804850 - Output will be ignored
2025-04-04T21:13:34.804850 - Failed to validate prompt for output 82:
2025-04-04T21:13:34.805848 - Output will be ignored
2025-04-04T21:13:34.805848 - Failed to validate prompt for output 63:
2025-04-04T21:13:34.805848 - Output will be ignored
2025-04-04T21:13:34.900127 - [92mPolymath Chat Request: [0mModel='Ollama: trollek/qwen2-diffusion-prompter latest', Prompt='Please provide only the SDXL prompt, nothing extra.

Please describe an emotive sequence stunning solo adult female portrait. Any dramatic setting. in a random pose.

Please only give me the prompt.

Please expand this prompt with a lot more fictional detail, no adult theme
', Additional Text=''2025-04-04T21:13:34.902654 -  2025-04-04T21:13:34.908001 - Seed='245990022', Web Search Enabled=False, Keep Context=False,Ollama Chat Mode=False, Custom Instruction='expert prompter'2025-04-04T21:13:34.908001 - 
2025-04-04T21:13:42.473471 - Ollama API Response:2025-04-04T21:13:42.474022 -  2025-04-04T21:13:42.474022 - Portrait of 18 years old, very skilled and stylish porn actress, dark sexy mood, in her favorite retro clothing, wearing an oversized bikini top and thigh-high boots sitting at a kitchen counter in a kitchen, close-up on her face2025-04-04T21:13:42.474022 - 
2025-04-04T21:13:45.854698 - Requested to load SDXL
2025-04-04T21:13:47.368509 - loaded partially 3155.0583160400392 3155.0573806762695 545
2025-04-04T21:15:15.408018 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:28<00:00,  1.75s/it]2025-04-04T21:15:15.408018 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:28<00:00,  1.96s/it]2025-04-04T21:15:15.408018 - 
2025-04-04T21:15:15.410140 - Requested to load AutoencoderKL
2025-04-04T21:15:15.736307 - loaded completely 219.12644577026367 159.55708122253418 True
2025-04-04T21:15:16.225416 - [Tiled VAE]: input_size: torch.Size([1, 4, 128, 96]), tile_size: 64, padding: 112025-04-04T21:15:16.225416 - 
2025-04-04T21:15:16.225416 - [Tiled VAE]: split to 2x2 = 4 tiles. Optimal tile size 64x64, original tile size 64x642025-04-04T21:15:16.226420 - 
2025-04-04T21:15:16.238437 - [Tiled VAE]: Fast mode enabled, estimating group norm parameters on 48 x 64 image2025-04-04T21:15:16.238437 - 
2025-04-04T21:15:17.528369 - 
[Tiled VAE]: Executing Decoder Task Queue:  75%|██████████████████████████▎        | 370/492 [00:01<00:00, 355.52it/s]2025-04-04T21:15:17.570621 - 
[Tiled VAE]: Executing Decoder Task Queue: 100%|███████████████████████████████████| 492/492 [00:01<00:00, 439.77it/s]2025-04-04T21:15:17.570621 - 
2025-04-04T21:15:18.182141 - [Tiled VAE]: Done in 2.440s, max VRAM alloc 2189.997 MB2025-04-04T21:15:18.182141 - 
2025-04-04T21:15:19.787414 - loaded partially 3155.5277565002443 3155.526741027832 0
2025-04-04T21:15:55.246428 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:35<00:00,  1.75s/it]2025-04-04T21:15:55.246428 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:35<00:00,  1.77s/it]2025-04-04T21:15:55.246428 - 
2025-04-04T21:15:55.327484 - Requested to load AutoencoderKL
2025-04-04T21:15:55.627550 - loaded completely 252.95843505859375 159.55708122253418 True
2025-04-04T21:15:56.099584 - [Tiled VAE]: input_size: torch.Size([1, 4, 128, 96]), tile_size: 64, padding: 112025-04-04T21:15:56.099584 - 
2025-04-04T21:15:56.099584 - [Tiled VAE]: split to 2x2 = 4 tiles. Optimal tile size 64x64, original tile size 64x642025-04-04T21:15:56.099584 - 
2025-04-04T21:15:56.101511 - [Tiled VAE]: Fast mode enabled, estimating group norm parameters on 48 x 64 image2025-04-04T21:15:56.101511 - 
2025-04-04T21:15:57.386768 - 
[Tiled VAE]: Executing Decoder Task Queue:  75%|██████████████████████████▎        | 370/492 [00:01<00:00, 355.21it/s]2025-04-04T21:15:57.430047 - 
[Tiled VAE]: Executing Decoder Task Queue: 100%|███████████████████████████████████| 492/492 [00:01<00:00, 440.32it/s]2025-04-04T21:15:57.430047 - 
2025-04-04T21:15:58.026055 - [Tiled VAE]: Done in 2.395s, max VRAM alloc 2164.977 MB2025-04-04T21:15:58.026055 - 
2025-04-04T21:16:12.733913 - Requested to load AutoencoderKL
2025-04-04T21:16:12.771551 - 0 models unloaded.
2025-04-04T21:16:12.811201 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:16:13.991927 - Requested to load SDXL
2025-04-04T21:16:15.010020 - loaded partially 3154.6841819763185 3154.6838455200195 0
2025-04-04T21:17:11.370215 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:56<00:00,  2.81s/it]2025-04-04T21:17:11.370215 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:56<00:00,  2.82s/it]2025-04-04T21:17:11.370215 - 
2025-04-04T21:17:11.374215 - Requested to load AutoencoderKL
2025-04-04T21:17:14.870920 - 0 models unloaded.
2025-04-04T21:17:14.915704 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:17:22.945627 - 
2025-04-04T21:17:23.012340 - 0: 640x480 1 face, 37.1ms
2025-04-04T21:17:23.012340 - Speed: 4.0ms preprocess, 37.1ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 480)
2025-04-04T21:17:24.071411 - CLIP: [Love, Cheekbones]2025-04-04T21:17:24.071411 - 
2025-04-04T21:17:27.785325 - Detailer: force inpaint2025-04-04T21:17:27.785325 - 
2025-04-04T21:17:27.785325 - Detailer: segment upscale for ((352.31616, 360.72552)) | crop region (1056, 1082) x 1.0 -> (1056, 1082)2025-04-04T21:17:27.785325 - 
2025-04-04T21:17:27.908824 - 0 models unloaded.
2025-04-04T21:17:27.912338 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:17:29.031522 - 0 models unloaded.
2025-04-04T21:17:29.036522 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:17:29.925980 - Requested to load SDXL
2025-04-04T21:17:31.762449 - loaded partially 3150.6336601257326 3150.632942199707 546
2025-04-04T21:19:14.568333 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:42<00:00,  2.52s/it]2025-04-04T21:19:14.568842 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:42<00:00,  2.28s/it]2025-04-04T21:19:14.568842 - 
2025-04-04T21:19:14.704911 - 0 models unloaded.
2025-04-04T21:19:14.775710 - loaded partially 3150.6329422950744 3150.632942199707 0
2025-04-04T21:20:57.255712 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:42<00:00,  2.21s/it]2025-04-04T21:20:57.255712 - 
100%|█████████████████████████████████████████████████████████████████████████████████| 45/45 [01:42<00:00,  2.28s/it]2025-04-04T21:20:57.255712 - 
2025-04-04T21:20:57.258232 - Requested to load AutoencoderKL
2025-04-04T21:20:59.158307 - 0 models unloaded.
2025-04-04T21:20:59.197862 - loaded partially 128.0 127.99993133544922 0
2025-04-04T21:21:00.618622 - [Impact Pack] vae decoded in 3.4s2025-04-04T21:21:00.618622 - 
2025-04-04T21:21:00.871776 - 
2025-04-04T21:21:00.937273 - 0: 640x480 (no detections), 32.8ms
2025-04-04T21:21:00.937273 - Speed: 3.0ms preprocess, 32.8ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 480)
2025-04-04T21:21:01.482190 - 执行命令: C:\Program Files\Topaz Labs LLC\Topaz Gigapixel AI\gigapixel.exe --scale 2.0 -i C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\temp\gigapixel_output\batch_1743816061147\input_1.png -o C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\temp\gigapixel_output\batch_1743816061147\output_1 --dn 1.0 --sh 1.0 --cm 67.0 --fr 50.0 --model fidelity --mv 22025-04-04T21:21:01.482190 - 
2025-04-04T21:23:21.331723 - Gigapixel CLI error code: 42949672942025-04-04T21:23:21.331723 - 
2025-04-04T21:23:21.332734 - STDOUT: Running CLI
Time to run CLI: "314.102 ms"
2025-04-04T21:23:21.332734 - 
2025-04-04T21:23:21.332734 - STDERR: Invalid auth token. Please login through the app.
2025-04-04T21:23:21.332734 - 
2025-04-04T21:23:21.348296 - !!! Exception during processing !!! Command '['C:\\Program Files\\Topaz Labs LLC\\Topaz Gigapixel AI\\gigapixel.exe', '--scale', '2.0', '-i', 'C:\\COMFYUI\\COMFYU2\\CFUI2\\ComfyUI\\temp\\gigapixel_output\\batch_1743816061147\\input_1.png', '-o', 'C:\\COMFYUI\\COMFYU2\\CFUI2\\ComfyUI\\temp\\gigapixel_output\\batch_1743816061147\\output_1', '--dn', '1.0', '--sh', '1.0', '--cm', '67.0', '--fr', '50.0', '--model', 'fidelity', '--mv', '2']' returned non-zero exit status 4294967294.
2025-04-04T21:23:21.379980 - Traceback (most recent call last):
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\ComfyUI-GigapixelAI\gigapixel.py", line 146, in upscale_image
    (settings, output_image_paths) = self.gigapixel_upscale(img_file, gigapixel_exe, scale, upscale, model, output_dir)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI\COMFYU2\CFUI2\ComfyUI\custom_nodes\ComfyUI-GigapixelAI\gigapixel.py", line 210, in gigapixel_upscale
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "C:\Users\ZUSIMA.DESKTOP-FG9LLK8\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Topaz Labs LLC\\Topaz Gigapixel AI\\gigapixel.exe', '--scale', '2.0', '-i', 'C:\\COMFYUI\\COMFYU2\\CFUI2\\ComfyUI\\temp\\gigapixel_output\\batch_1743816061147\\input_1.png', '-o', 'C:\\COMFYUI\\COMFYU2\\CFUI2\\ComfyUI\\temp\\gigapixel_output\\batch_1743816061147\\output_1', '--dn', '1.0', '--sh', '1.0', '--cm', '67.0', '--fr', '50.0', '--model', 'fidelity', '--mv', '2']' returned non-zero exit status 4294967294.

2025-04-04T21:23:21.382497 - Prompt executed in 586.57 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by sh570655308** [comment]
2025-04-04T21:23:21.332734 - STDERR: Invalid auth token. Please login through the app.

**Comment by S0LTIS** [comment]
> 2025-04-04T21:23:21.332734 - STDERR: Invalid auth token. Please login through the app.

Thanks, it worked!
